Eddy arm code
FRC2706/2023-2706-Robot-Code pull request #107
Opened 2023-04-01 18:57 UTC by edwardwang4340

2023-04-01 19:02 UTC, ErikCald approved these changes

2023-04-01 19:19 UTC, weizhang-2706 requested changes

2023-04-01 19:19 UTC, weizhang-2706 commented on src/main/java/frc/robot/subsystems/ArmSubsystem.java
> +  // for nose-in/base-in cones
If you don't use this, you can clean it up.

2023-04-01 22:24 UTC, weizhang-2706 approved these changes

2023-04-01 22:25 UTC, merged

2023-04-03 04:11 UTC, ErikCald commented
Closes #104