Emily arm break controls
FRC2706/2023-2706-Robot-Code pull request #34
Opened 2023-01-29 23:45 UTC by emilycxliu

2023-01-31 00:07 UTC, weizhang-2706 approved these changes

2023-01-31 15:31 UTC, ErikCald requested changes
For the pistons on the brakes, you only need to set kForward and kReverse.

I'm not sure what setting kOff will do but I don't think it will do what you want, and the stopLowBreak/stopHighBreak might get confusing if other people want to use them to control the brakes.

2023-02-01 00:07 UTC, emilycxliu commented
controlTopArmBreak() can set the break on or off.
stopHighBreak() doesn't control the break. i can change its name to stopControlBreak() instead.

2023-02-01 00:21 UTC, ErikCald approved these changes

2023-02-01 00:30 UTC, merged