Albert intake claw
FRC2706/2023-2706-Robot-Code pull request #35
Opened 2023-01-31 01:25 UTC by egg625

Intake Subsystem Intake, Command

2023-01-31 01:50 UTC, weizhang-2706 approved these changes

2023-01-31 16:21 UTC, ErikCald requested changes
There is a null pointer exception that is crashing the code.

IntakeSubsystem.getInstance() returns a null value if the pneumatic channel id's for the pistons are equal to -1.

IntakeCommand then uses that null value and get's a null pointer exception.

A few options to fix:
1. Handle the null in the IntakeCommand
2. Remove the stuff that checks if there are pneumatics. The libraries should be able to handle it if there are no pneumatics there, no real need to check if they are valid.

Reach out to a mentor during tomorrow's meeting if you need help.
1.

2023-02-02 01:19 UTC, egg625 commented
I believe that the null exception has been fixed

2023-02-02 03:42 UTC, ErikCald approved these changes

2023-02-02 03:44 UTC, merged