flipped width and lengths
FRC2706/2023-2706-Robot-Code pull request #54
Opened 2023-02-18 19:44 UTC by emilycxliu

2023-02-27 16:45 UTC, ErikCald requested changes

2023-02-27 16:45 UTC, ErikCald commented on src/main/java/frc/robot/config/Config.java
> +            new Translation2d(kWheelBase / 2, -kTrackWidth / 2));
Remove this change to SwerveDriveKinematics. Swapping around the negative and positive signs here was to temporarily allow the swervy beetle to have a different front. On the CompBot, we'll need the original order of positive and negative signs.

2023-03-01 23:04 UTC, weizhang-2706 approved these changes

2023-03-01 23:40 UTC, ErikCald approved these changes

2023-03-01 23:41 UTC, merged