-Added more animations (RgbFade and Strobe)
FRC2706/2023-2706-Robot-Code pull request #55
Opened 2023-02-23 00:52 UTC by cooking-hambrops

-Modified current animations

2023-02-23 00:59 UTC, weizhang-2706 requested changes

2023-02-23 00:59 UTC, weizhang-2706 commented on src/main/java/frc/robot/subsystems/BlingSubsystem.java
> +import com.ctre.phoenix.led.RgbFadeAnimation;
I don't think you still need to import these Animations, since they are in SetBlingCommand class now.
So remove them from BlingSubsystem.

2023-02-26 14:34 UTC, weizhang-2706 approved these changes

2023-02-27 16:41 UTC, ErikCald approved these changes

2023-02-27 16:41 UTC, merged