added the new game piece robot state
FRC2706/2023-2706-Robot-Code pull request #60
Opened 2023-03-04 14:43 UTC by emilycxliu

2023-03-04 14:47 UTC, weizhang-2706 approved these changes

2023-03-04 14:49 UTC, emilycxliu commented
the arm command is just an example to show the constructor's interface.
more examples of the constructor are put in the configure button bindings.

2023-03-04 16:10 UTC, ErikCald requested changes
Can you rename ArmCommand to something else? Eddy already has a command named ArmCommand so it would cause a merge conflict.

Just rename it to ArmCommandExample or something.

2023-03-05 00:15 UTC, ErikCald approved these changes

2023-03-05 00:20 UTC, merged