added arm command selector
FRC2706/2023-2706-Robot-Code pull request #65
Opened 2023-03-07 00:31 UTC by emilycxliu

selector will choose the arm command based on the game piece type and target position.

2023-03-07 00:38 UTC, weizhang-2706 approved these changes

2023-03-07 04:06 UTC, ErikCald requested changes
This command should handle the cases for TOP, MIDDLE, BOTTOM and for pickup as well. I think it would be better to add a specific ArmPosition for pickup than have pickup be the default option.

2023-03-07 04:06 UTC, ErikCald commented on src/main/java/frc/robot/commands/ArmCommandSelector.java
> +    m_robotState = robotState.get();
The robotState will change a lot during a match. Here you're getting the robot state when the command is first constructed and then only using that state. Instead, you will need to get the state in initialize() and then check which state it is.

2023-03-07 04:06 UTC, ErikCald commented on src/main/java/frc/robot/commands/ArmCommandSelector.java
> +        m_ArmSetPoint = ArmSetpoint.HOME_WITH_GAMEPIECE;
The NoGamePiece arm setpoint should be ArmSetpoint.CONE_PICKUP instead.

2023-03-08 20:21 UTC, ErikCald approved these changes
This can merge.

Note that the slowerAcceleration boolean was moved to inside the ArmSetpoint enum, but it hasn't been removed from the constructor of ArmCommand yet.

Soon, someone will need to remove that boolean from ArmCommandSelector and remove it from the constructor of ArmCommand.

2023-03-08 20:21 UTC, merged