added the analog selector for the autoroutine
FRC2706/2023-2706-Robot-Code pull request #71
Opened 2023-03-10 23:18 UTC by emilycxliu

2023-03-10 23:31 UTC, weizhang-2706 approved these changes

2023-03-11 02:18 UTC, weizhang-2706 requested changes

2023-03-11 02:18 UTC, weizhang-2706 commented on src/main/java/frc/robot/auto/AutoSelector.java
> +            case "Select Autonomous...  ":
Add a space between Autonomous and ...

2023-03-11 02:20 UTC, weizhang-2706 requested changes

2023-03-11 02:20 UTC, weizhang-2706 commented on src/main/java/frc/robot/auto/AutoSelector.java
> +        System.out.println(autoName);
change to System.out.println("FRC Dashboard autoName " + autoName);

2023-03-11 03:13 UTC, ErikCald approved these changes

2023-03-11 16:35 UTC, weizhang-2706 approved these changes

2023-03-11 16:43 UTC, merged