Updated auto routines.
FRC2706/2023-2706-Robot-Code pull request #76
Opened 2023-03-13 02:09 UTC by emilycxliu

Including the auto routine tested in Kingston.

2023-03-13 23:03 UTC, ErikCald requested changes
I think you deleted too many paths.

There were some cone paths that we tested at the library. We might decide to not use them or delete them later but I don't think we should remove them right now.

Here's a list of the ones (PathPlanner path names) that I think should not be deleted (but they do need renaming):
- place_pick_bottom2_charge_new
- place_pick_place_pick_place_bottom2
- place_pick_place_pick_place_bottom2_charge
- place_pick_place_pick_place_bottom_new

Some of these should be deleted later once we decide which ones to focus on for Humber.

2023-03-14 13:08 UTC, weizhang-2706 approved these changes

2023-03-14 13:10 UTC, weizhang-2706 commented
We need to finalize the auto routines for competitions and remove all the unused ones. 
I am thinking loading those paths at the beginning could be a reason to delay encoders in-sync.

2023-03-14 15:22 UTC, ErikCald approved these changes

2023-03-14 15:23 UTC, merged