Jamie balance lock
FRC2706/2023-2706-Robot-Code pull request #77
Opened 2023-03-13 21:48 UTC by Jdiep7

2023-03-13 22:33 UTC, ErikCald requested changes
In the command, the code in initialize should instead run in execute. Motor safety is suppose to stop the steering motors from working if it's only set once, so it needs to be set every robot cycle instead.

2023-03-13 22:51 UTC, ErikCald commented
The  command needs to have addRequirements for the SwerveSubsystem. Otherwise the teleop command and this command will both ask for swerve motor control at the same time. This command needs to forceful unschedule the TeleopSwerve command while true.

2023-03-14 14:00 UTC, ErikCald approved these changes

2023-03-14 14:14 UTC, merged

2023-03-14 14:14 UTC, weizhang-2706 approved these changes